compatibility_date = "2024-03-27"
name = "nosflare"
workers_dev = false
main = "dist/worker.js"
kv_namespaces = [
    { binding = "relayDb", id = "KV_ID" }
]
routes = [
	{ pattern = "FULL_DOMAIN", zone_name = "DOMAIN" }
]
